### ISSUE TITLE
acronym first use not recognized in xltabular

### ISSUE THREAD

**Issue by DaveInWellesley** [oetiker/acronym#38] opened 2020-12-02 23:09 UTC
When using xltabular (or tabularx, I believe), the first use of an acronym is not recognized, so each occurrence in a table gets its own footnote.  If the acronym has been used prior to being used in a table, the usage in the table does not result in additional footnotes.

I have attached a minimum working example.

[MWE.zip](https://github.com/oetiker/acronym/files/5632584/MWE.zip)

And thanks for this very useful package!

     Dave Underwood

**Comment by marsmee** [comment] 2021-07-09 16:47
Duplicate of https://github.com/oetiker/acronym/issues/11.
Some environments, like `tabularx`, cannot handle macros with side effects. The only chance to consistently get the same result in such environments is to use the side-effect-free macros of this package, like `\acs`, `\acl`, or `\acf`.

**Closed by marsmee** 2021-07-09 16:47 UTC

**Comment by DaveInWellesley** [comment] 2021-07-10 15:07
So, after reading posts for [#11](https://github.com/oetiker/acronym/issues/11) and [#6](https://github.com/oetiker/acronym/issues/6) the underlying problem is much clearer.  Thanks for your response.
