### ISSUE TITLE
Fix forward links in list of acronyms cases where only \acs is used in text

### ISSUE THREAD

**Issue by notjustanygeek** [oetiker/acronym#51] opened 2023-02-17 03:22 UTC
I have a long document with many chapters and a long list of acronyms. I appreciate the forward links feature of this package which takes you from the LoAs to the first usage. However, for stylistic reasons, several of my acronyms are used for the first time, or only, in the short form and so these hyperlinks are missing from my glossary. This looks strange because I have a list of acronyms that are blue and then scattered about are the various acronyms that I have used that don't have forward links associated with them and this is distressing. I have attempted to fool the compiler into thinking the acronym was called by putting \ac{myacronym} inside a \vphantom or similar construct, but this didn't work, nor did calling \acused{myacronym}. Can you please provide a workaround?

**Comment by notjustanygeek** [comment] 2023-02-17 03:24
note, my supervisor has asked me to keep the hyperlinks blue because he finds them helpful so an aesthetic change isn't an option for me.

**Comment by chrislandis** [comment] 2024-03-26 02:34
I recommend closing this issue as a duplicate of issue #32.

**Closed** 2024-03-26 07:16 UTC
